version: "3.9"

services:
  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
  rails:
    container_name: rails_pj-group5
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: development #追加
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - rails
volumes:
  db-volume:
    driver: local
  bundle:
    driver: local
  public-data:
  tmp-data:
  log-data: