default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV['DATABASE_HOST'] %> # Dockerをつかっている場合こっち使って

development:
  <<: *default
  database: myapp_development
  # host: 127.0.0.1 # 自分のマシンでrails sを実行する場合こっち使って

# see : https://qiita.com/koda_7932/items/6913ca184cb289e4ec16
production:
  <<: *default
  database: myapp_production
  username: <%= Rails.application.credentials.rds[:DATABASE_USERNAME] %>
  password: <%= Rails.application.credentials.rds[:DATABASE_PASSWORD] %>
  host: <%= Rails.application.credentials.rds[:DATABASE_HOST] %>
  socket: /var/lib/mysql/mysql.sock