# このファイルは、GitHub Actions でテスト/rubocopを実行するための設定ファイルです。
# 時間があればreviewdogを導入したい
# - https://qiita.com/ken1flan/items/a28e08eee5e5cf061232
name: "test"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Set up database schema
        # env:
        #   RAILS_ENV: test
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rake db:create
          bundle exec rake db:migrate
      - name: Run tests
        run: bundle exec rails test
  Job-Rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby Env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Show ruby version
        run: ruby -v

      - name: Run lint
        run: bundle exec rubocop
